const STORAGE_KEY = 'admin_products';

const defaultProducts = [
    // ADAPTERS
    {
        id: "BC_01",
        name: "USB-C to USB Adapter",
        price: 25,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST2U-nwg6gwNxPkR1eP-EqguPvii8z8BrSQg&s",
        type: "adapters",
        compatibleDevices: ["Samsung", "iPhone", "iPad"],
        rating: 4,
        isHot: false,
    },
    {
        id: "BC_02",
        name: "Lightning to USB-C Adapter",
        price: 30,
        image: "https://www.technocratng.com/wp-content/uploads/2021/02/APPLE-USB-C-TO-LIGHTNING-ADAPTER.png",
        type: "adapters",
        compatibleDevices: ["iPhone", "iPad"],
        rating: 4,
        isHot: false,
    },
    {
        id: "BL_01",
        name: "Type-C to HDMI Adapter",
        price: 45,
        image: "https://ascrono.com/cdn/shop/products/ctohdmi.png?v=1614686906",
        type: "adapters",
        compatibleDevices: ["Samsung", "MacBook"],
        rating: 5,
        isHot: true,
    },
    {
        id: "AD_01",
        name: "Multi-Port USB Hub",
        price: 55,
        image: "https://www.amkette.com/cdn/shop/files/1PNG_db7c703a-cd0c-4d2e-9c6f-93039dee2219.png?v=1684994905",
        type: "adapters",
        compatibleDevices: ["Universal"],
        rating: 5,
        isHot: true,
    },
    {
        id: "AD_02",
        name: "USB-C to VGA Adapter",
        price: 35,
        image: "https://shop.xtrememac.com/cdn/shop/products/ScreenShot2022-10-17at4.17.13PM.png?v=1666016259",
        type: "adapters",
        compatibleDevices: ["MacBook", "Dell", "HP"],
        rating: 4,
        isHot: false,
    },
    {
        id: "AD_03",
        name: "Mini DisplayPort to HDMI",
        price: 28,
        image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/ugreen-minidp-tohdmi-converter1080p-11_2048x2048_918aaa5d-50bf-4e58-b44a-5f97ce9df99a.png?v=1736236162",
        type: "adapters",
        compatibleDevices: ["MacBook", "Surface"],
        rating: 4,
        isHot: false,
    },
    {
        id: "AD_04",
        name: "Ethernet to USB-C Adapter",
        price: 38,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA9U5zbNxihG_LDD1JbzO_FCXT6apUHuW19A&s",
        type: "adapters",
        compatibleDevices: ["Universal"],
        rating: 5,
        isHot: false,
    },
    {
        id: "AD_05",
        name: "USB 3.0 to Ethernet",
        price: 32,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4uPcN3pWxwxKIhAEJtCel3UmzJ_Hz64iesw&s",
        type: "adapters",
        compatibleDevices: ["Universal"],
        rating: 4,
        isHot: false,
    },
    {
        id: "AD_06",
        name: "USB-C to 3.5mm Audio Jack",
        price: 22,
        image: "https://www.mag-kabel.de/images/product_images/original_images/USBC-AUDIO-S-KB_2.png",
        type: "adapters",
        compatibleDevices: ["Samsung", "Google Pixel", "iPad Pro"],
        rating: 4,
        isHot: false,
    },
    {
        id: "AD_07",
        name: "Thunderbolt 3 to Dual HDMI",
        price: 68,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQVtKqLeJ15nnSu4Sqo56-D_3P1VAhtWQGaQ&s",
        type: "adapters",
        compatibleDevices: ["MacBook Pro", "Dell XPS"],
        rating: 5,
        isHot: true,
    },

    // CHARGERS
    {
        id: "CH_01",
        name: "Fast Wall Charger 20W",
        price: 42,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6chIS17sn0knvBwvLXwDm0q2vATfEXOlStA&s",
        type: "chargers",
        compatibleDevices: ["iPhone", "Samsung"],
        rating: 5,
        isHot: true,
    },
    {
        id: "CH_02",
        name: "Dual USB Wall Charger",
        price: 35,
        image: "https://www.walkntalk.com.au/cdn/shop/files/20W_Dual_USB_Wall_Charger.png?v=1714533881&width=2048",
        type: "chargers",
        compatibleDevices: ["Universal"],
        rating: 4,
        isHot: false,
    },
    {
        id: "CH_03",
        name: "USB-C PD Charger 65W",
        price: 58,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE8yYFZ2UU3vLfVwg3pOhZoaAyNCodI_CXSg&s",
        type: "chargers",
        compatibleDevices: ["MacBook", "iPad", "Samsung"],
        rating: 5,
        isHot: true,
    },
    {
        id: "CH_04",
        name: "Wireless Charging Pad",
        price: 48,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBrvfGpQsnTLagFMtmXqbEFMP3yZwcjAk5zA&s",
        type: "chargers",
        compatibleDevices: ["iPhone", "Samsung", "AirPods"],
        rating: 4,
        isHot: true,
    },
    {
        id: "CH_05",
        name: "3-in-1 Wireless Charger",
        price: 75,
        image: "https://www.cygnett.com/cdn/shop/files/CY5069CCRGP-1_2376x.png?v=1727231620",
        type: "chargers",
        compatibleDevices: ["iPhone", "Apple Watch", "AirPods"],
        rating: 5,
        isHot: true,
    },
    {
        id: "CH_06",
        name: "Car Charger Dual Port",
        price: 28,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKxsm6h4zOUdBxa7ylvUSKaAu4BSJH0nRJHg&s",
        type: "chargers",
        compatibleDevices: ["Universal"],
        rating: 4,
        isHot: false,
    },
    {
        id: "CH_07",
        name: "Portable Power Bank 10000mAh",
        price: 45,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLtjIdHaNUXlDcl2dU2mD6iVvN7iRbFHxeAg&s",
        type: "chargers",
        compatibleDevices: ["Universal"],
        rating: 5,
        isHot: true,
    },
    {
        id: "CH_08",
        name: "GaN Charger 100W",
        price: 68,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9MVykm1_P15OH1fnrypkQuoCc50AvJh4Pew&s",
        type: "chargers",
        compatibleDevices: ["MacBook", "iPad", "iPhone"],
        rating: 5,
        isHot: true,
    },
    {
        id: "CH_09",
        name: "Desktop Charging Station",
        price: 52,
        image: "https://png.pngtree.com/png-vector/20250317/ourmid/pngtree-multi-port-phone-stand-for-efficient-charging-png-image_15763798.png",
        type: "chargers",
        compatibleDevices: ["Universal"],
        rating: 4,
        isHot: false,
    },
    {
        id: "CH_10",
        name: "Magnetic Wireless Charger",
        price: 38,
        image: "https://png.pngtree.com/png-vector/20240726/ourmid/pngtree-magnetic-wireless-charging-png-image_13137290.png",
        type: "chargers",
        compatibleDevices: ["iPhone 12+"],
        rating: 5,
        isHot: true,
    },

    // EARPHONES
    {
        id: "EP_01",
        name: "USB-C Wired Earphones",
        price: 22,
        image: "https://www.belkin.com/dw/image/v2/BGBH_PRD/on/demandware.static/-/Sites-master-product-catalog-blk/default/dw7f47c6d0/images/hi-res/d/125861402525eb9b_G3H0002btBLK_SoundFormWiredEarbudswithUSB-CConnector_01_web.jpg?sfrm=png",
        type: "earphones",
        compatibleDevices: ["Samsung", "iPad", "MacBook"],
        connector: "Type-C",
        rating: 4,
        isHot: false,
    },
    {
        id: "EP_02",
        name: "Lightning Earphones",
        price: 25,
        image: "https://www.belkin.com/dw/image/v2/BGBH_PRD/on/demandware.static/-/Sites-master-product-catalog-blk/default/dw0c239383/images/hi-res/1/1bec74bf86d9843f_G3H0001_BLK_FPK_JY_FIN.jpg?sfrm=png",
        type: "earphones",
        compatibleDevices: ["iPhone", "iPad"],
        connector: "Lightning",
        rating: 4,
        isHot: false,
    },
    {
        id: "EP_03",
        name: "3.5mm Jack Earphones",
        price: 18,
        image: "https://www.firstshop.co.za/cdn/shop/files/mwu53zm-a-headsets-45732496703652.png?v=1722300398",
        type: "earphones",
        compatibleDevices: ["Universal"],
        connector: "Jack",
        rating: 3,
        isHot: false,
    },
    {
        id: "EP_04",
        name: "USB-C Noise Cancelling",
        price: 48,
        image: "https://d287ku8w5owj51.cloudfront.net/images/products/hero/creative-chat-usb/hero-chat-usb.png?width=1200&height=600",
        type: "earphones",
        compatibleDevices: ["Samsung", "Google Pixel"],
        connector: "Type-C",
        rating: 5,
        isHot: true,
    },
    {
        id: "EP_05",
        name: "Premium Lightning Earbuds",
        price: 45,
        image: "https://png.pngtree.com/png-vector/20250416/ourmid/pngtree-white-airpods-wireless-earphones-with-charging-case-isolated-on-transparent-background-png-image_16032402.png",
        type: "earphones",
        compatibleDevices: ["iPhone", "iPad"],
        connector: "Lightning",
        rating: 5,
        isHot: true,
    },
    {
        id: "EP_06",
        name: "Sport USB-C Earphones",
        price: 32,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK5ucky1q8tBGCiGndJzfWDxJEuNrJLQSYGg&s",
        type: "earphones",
        compatibleDevices: ["Samsung", "OnePlus"],
        connector: "Type-C",
        rating: 4,
        isHot: false,
    },
    {
        id: "EP_07",
        name: "In-Ear 3.5mm Earphones",
        price: 15,
        image: "https://gadgetngadgetbd.com/assets/images/backend/product/featured/67ff8a4220f5e1744800322.png",
        type: "earphones",
        compatibleDevices: ["Universal"],
        connector: "Jack",
        rating: 3,
        isHot: false,
    },
    {
        id: "EP_08",
        name: "Studio USB-C Earphones",
        price: 55,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjmxPZ40eNQGJKWIg1nBas54FbZlO9X3EAFA&s",
        type: "earphones",
        compatibleDevices: ["Samsung", "iPad Pro"],
        connector: "Type-C",
        rating: 5,
        isHot: true,
    },
    {
        id: "EP_09",
        name: "Gaming Lightning Earphones",
        price: 42,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrbp4iX7XaBhEP7nZmdP1Nnj6E4NmJTjFybA&s",
        type: "earphones",
        compatibleDevices: ["iPhone", "iPad"],
        connector: "Lightning",
        rating: 4,
        isHot: false,
    },
    {
        id: "EP_10",
        name: "Classic 3.5mm Earbuds",
        price: 12,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHlqhmb5zjrMy5rrVEuFE5nHLNUvkzvtEWbA&s",
        type: "earphones",
        compatibleDevices: ["Universal"],
        connector: "Jack",
        rating: 3,
        isHot: false,
    },
    // DATA CABLES
    {
        id: "DC_01",
        name: "Fast Data Cable USB-C to USB-C",
        price: 25,
        image: "https://shareefcorner.sa/media/catalog/product/cache/d4cc45832d2a6689466075a3e554546c/d/c/dc21d.png",
        type: "data-cables",
        compatibleDevices: ["Samsung", "MacBook", "iPad"],
        connector: "USB to Type-C",
        rating: 5,
        isHot: true,
    },
    {
        id: "DC_02",
        name: "Premium Braided Lightning Cable",
        price: 30,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVW5aZ4ObUNDj1cIMVBLpulfNE3P5CSUdZwA&s", // Placeholder url
        type: "data-cables",
        compatibleDevices: ["iPhone", "iPad"],
        connector: "USB to Lightning",
        rating: 4,
        isHot: false,
    },
    {
        id: "DC_03",
        name: "Micro USB Cable 2M",
        price: 15,
        image: "https://www.powerpod.net/cdn/shop/products/MicroUSB2m_grande.png?v=1623290360",
        type: "data-cables",
        compatibleDevices: ["Older Android", "Kindle", "Power Bank"],
        connector: "USB to Micro",
        rating: 3,
        isHot: false,
    },
    {
        id: "DC_04",
        name: "AUX Cable 3.5mm",
        price: 12,
        image: "https://www.wentronic.com/media/perfion/perfion-product/dbbf72ed-798b-453d-97a2-3d5490b47a3c-65272-65276_dyna.png.jpg",
        type: "data-cables",
        compatibleDevices: ["Universal"],
        connector: "Jack to Jack",
        rating: 4,
        isHot: false,
    },
    {
        id: "DC_05",
        name: "Audio Adapter Jack to Type-C",
        price: 20,
        image: "https://i5.walmartimages.com/seo/USB-C-3-5mm-Headphone-Jack-Dongle-Adapter-Type-Audio-Converter-Nylon-Cable-Compatible-Samsung-Galaxy-S20-Ultra-Note-10-S10-S9-Plus-iPad-Pro-2018-2019_f06c0430-8a3d-4129-b8ad-e96aca7ff440.6874c0945a18ab1db09ee21661bf7588.png?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
        type: "data-cables",
        compatibleDevices: ["Samsung", "iPad"],
        connector: "Jack to Type-C",
        rating: 4,
        isHot: false,
    },

    // CAR CHARGERS
    {
        id: "CC_01",
        name: "Dual Port Car Charger",
        price: 25,

        image: "https://i5.walmartimages.com/seo/Anker-Car-Charger-USB-C-35W-2-Port-Compact-Type-C-Car-Charger-20W-Power-Delivery-15W-PowerIQ-2-0-PowerDrive-PD-2-Car-Charger-iPhone-12-11-X-8-Pixel-3_3588edce-5033-464a-9f36-fc0aec1bf6b5.1a93c82e329d9fe55d6655937d5c987b.png",
        type: "car-charger",
        compatibleDevices: ["Universal"],
        connector: "USB to Micro",
        rating: 4,
        isHot: false,
    },
    {
        id: "CC_02",
        name: "Fast Car Charger PD 30W",
        price: 45,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSZvgW_4OtSu_uY1QWG46PIA8E_3Ouoy1iWg&s",
        type: "car-charger",
        compatibleDevices: ["iPhone", "Samsung"],
        connector: "USB to C",
        rating: 5,
        isHot: true,
    },
    {
        id: "CC_03",
        name: "Car Charger with Lightning Cable",
        price: 35,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5lPWSsj4chqxlmmGqWXOqETEbXINHjsYy6Q&s",
        type: "car-charger",
        compatibleDevices: ["iPhone", "iPad"],
        connector: "USB to Lightning",
        rating: 4,
        isHot: false,
    },
    {
        id: "CC_04",
        name: "High Power Car Charger 45W",
        price: 55,
        image: "https://iaohi.com/cdn/shop/files/01-_01.png?v=1741689281&width=1600",
        type: "car-charger",
        compatibleDevices: ["MacBook Air", "Tablets"],
        connector: "USB to C",
        rating: 5,
        isHot: true,
    },
    {
        id: "CC_05",
        name: "Mini Car Charger",
        price: 18,
        image: "https://gridgear.in/cdn/shop/files/blackcolor.png?v=1752007184",
        type: "car-charger",
        compatibleDevices: ["Universal"],
        connector: "Car Only",
        rating: 4,
        isHot: false,
    },

    // GLASS PROTECTION
    {
        id: "GP_01",
        name: "Clear Glass Screen Protector",
        price: 15,

        image: "https://png.pngtree.com/png-vector/20221110/ourmid/pngtree-stock-vector-illustration-isolated-on-white-background-of-either-tempered-glass-or-film-screen-protector-vector-png-image_40363024.jpg",
        type: "glass-protection",
        compatibleDevices: ["iPhone 13", "iPhone 14"],
        connector: "Clear",
        rating: 5,
        isHot: true,
    },
    {
        id: "GP_02",
        name: "Privacy Glass Protector",
        price: 25,
        image: "https://www.momax.net/cdn/shop/files/00f22bbe5c249345e367e371784cfbe7.png?v=1733742823&width=1000",

        type: "glass-protection",
        compatibleDevices: ["Samsung S23"],
        connector: "Print",
        rating: 4,
        isHot: false,
    },
    {
        id: "GP_03",
        name: "Matte Finish Screen Guard",
        price: 20,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJzXN2qVATMJp2pb3o8MkrbruqH2TkVGumyg&s",
        type: "glass-protection",
        compatibleDevices: ["iPad Pro"],
        connector: "Clear",
        rating: 4,
        isHot: false,
    },
    {
        id: "GP_04",
        name: "UV Tempered Glass",
        price: 35,
        image: "https://winskart.co.in/cdn/shop/products/41KaFSzDXxL._SL1200_00bbf87c-8d05-45e0-b7bb-4fc8b3b66bcf.jpg?v=1678770353",

        type: "glass-protection",
        compatibleDevices: ["Samsung Curved"],
        connector: "Clear",
        rating: 5,
        isHot: true,
    },
    {
        id: "GP_05",
        name: "Camera Lens Protector",
        price: 12,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRooCRLqmoPvrMVICcqAGEtybxaN3ZaDd8SPg&s",
        type: "glass-protection",
        compatibleDevices: ["iPhone 14 Pro"],
        connector: "Clear",
        rating: 4,
        isHot: false,
    },
];

export const getProducts = () => {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(defaultProducts));
        return defaultProducts;
    }
    return JSON.parse(stored);
};

export const saveProduct = (product) => {
    const products = getProducts();
    const newProduct = {
        ...product,
        id: `PROD_${Date.now()}`,
    };
    const updatedProducts = [...products, newProduct];
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedProducts));
    return newProduct;
};

export const updateProduct = (updatedProduct) => {
    const products = getProducts();
    const newProducts = products.map(p => p.id === updatedProduct.id ? updatedProduct : p);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(newProducts));
    return updatedProduct;
};

export const deleteProduct = (id) => {
    const products = getProducts();
    const filteredProducts = products.filter((p) => p.id !== id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(filteredProducts));
    return filteredProducts;
};

export const initializeProducts = () => {
    getProducts();
}
